### ISSUE TITLE
Filerev always generates the same 8 character

### ISSUE THREAD

**Issue by saloumfall** [yeoman/grunt-filerev#104]
Filerev always generates the same 8 character hash when renaming my files. Is this normal? I've tried changing the options to use a different algorithm but the hash is never random.
thx

**Comment by sindresorhus** [comment]
The hash is of the file contents, not file names. Hashes are also never random, that's the whole point of them.

**Comment by saloumfall** [comment]
How I can do with the cache if the filename does not change to evry production build(deploy)
