### ISSUE TITLE
Deprecated ?

### ISSUE THREAD

**Issue by wiibaa** [yeoman/grunt-filerev#106]
Hello yeoman team,
any more detailed why this plugin/repo is marked as DEPRECATED ?
pointer to a replacement plugin ?

CC top commiter on this repo @sindresorhus

**Comment by sindresorhus** [comment]
No one is maintaining it.

**Comment by wiibaa** [comment]
OK so it is currently *UNMAINTAINED* as grunt-usemin.
I suppose it is because the main generator are now using gulp
Thanks for clarifying

**Comment by atdiff** [comment]
What has replaced this?  @sindresorhus @wiibaa   Is there another package to use?
