### ISSUE TITLE
After rename a sourcemap, sourceMappingURL should be updated with the new map file

### ISSUE THREAD

**Issue by dendril** [yeoman/grunt-filerev#62]
Hey all,

After run `filerev` with sourceMaps for JS and CSS, I found with there is none update of the `sourceMappingURL` pointing to the new `.map` file.

Current behavior:
1- a.js with sourceMappingURL=a.js.map
2- run filerev
3- a.12345678.js with sourceMappingURL=a.js.map

Expected behavior:
1- a.js with sourceMappingURL=a.js.map
2- run filerev
3- a.12345678.js with sourceMappingURL=a.12345678.js.map

Is there something complicated behind this issue?

Thanks!

**Comment by david-gang** [comment]
This is really annoying. I think it is best to switch back to 2.10

**Comment by duhseekoh** [comment]
+1

**Comment by eddiemonge** [comment]
Does sourceMappingURL point to the actual map file or the source file? Are the sourcemaps gettings revisioned as well?

**Comment by sgnl** [comment]
`sourceMappingURL` points to the map file.

The Source-map file are rev'd with the minified .js file but the `//sourceMappingURL=` comment in the minified files points to the non-rev'd file name.

**Comment by eddiemonge** [comment]
I kind of feel like sourcemaps should not be revisioned ... because they should not be in production code. Debugging should happen on dev code. The system that converts from dev to production should not be introducing new errors (if it does then that needs to be patched). Having source maps in production just sends unneeded extra data

**Comment by sgnl** [comment]
There are cases when you might need maps to catch unforeseen production bugs.

**Comment by eddiemonge** [comment]
waiting for code updates before #67 can be merged.

**Comment by stevenleija** [comment]
Has this been merged yet?

**Comment by travi** [comment]
Please get this merged in soon. 

Unfortunately, you can't even exclude sourcemaps from getting rev'ed because of the "feature" to ensure they are rev'ed in sync with the source files. Sourcemaps are valuable in production and are only downloaded when dev-tools are open, so there should be no reason for them not to be included. 

With the current state of this plugin, sourcemaps leave dev-tools in a broken state.

**Comment by ncthis** [comment]
Ok, let me try to get around updating #67 and see.

**Comment by PedroEsperanca** [comment]
@david-gang  going back to 2.0.0 doesn't seem to change the bahaviour

**Comment by david-gang** [comment]
@PedroEsperanca . It worked for me. I traced back when the change of the source map was made. I think it was made around 2.1, so i got back to 2

**Comment by yoshokatana** [comment]
Updated PR (#79) that can be merged.

**Comment by travi** [comment]
It appears that this is not quite fully fixed.

I've pulled down the updated version by pointing npm directly at `yeoman/grunt-filerev#e7ddab5849ce38e4cd5fb78db2fe8b9d623ad3c4`. After installation, an `npm list grunt-filerev` shows `grunt-filerev@2.2.0  (git+https://github.com/yeoman/grunt-filerev#e7ddab5849ce38e4cd5fb78db2fe8b9d623ad3c4)`.

Running the task, I get the following failure message: `Warning: ENOENT, no such file or directory 'c:\<path to file...>\app.css.map'`. Looking in the directory, it looks like the filenames for `app.css` and `app.css.map` got rev'ed appropriately, but the `sourceMapUrl` in `app.css` failed to update. Also note that this is the first file, alphabetically, in my list of files provided to the grunt task. All other files were left untouched after the failure.

Please let me know if there is something that I missed or if there is additional information that I could provide to dig deeper into this.

**Comment by yoshokatana** [comment]
Ah, I think the fix was only added for js files. Let me take a look...

**Comment by yoshokatana** [comment]
@travi PR #80 should fix that for you, and it makes dealing with the sourceMap comments more stable overall. :sparkles:
