### ISSUE TITLE
Affect attributes other than src=

### ISSUE THREAD

**Issue by mattkirwan** [yeoman/grunt-filerev#72]
I'm using filerev on a Nivo Slider implementation. Part of how Nivo works is to use the rel="" attribute on an image tag to use as the thumbnail source.

Eg: 
```
<img src="{{publicAssetsLocation}}img/banner_large_01.64a59f.jpg" alt="" rel="/assets/img/banner_small_001.jpg" />
```

As you can see filerev doesn't pick up the rel= attribute as  'something to revision'.

Will this be a likely addition, Javascript is not my strong point and didn't want to spend hours trying to figure out how to implement locally without mentioning it.

Thoughts?

Some pointers would be appreciated on how to implement would be greatly received.

Matt

**Comment by sindresorhus** [comment]
This task only revs filenames. You might be having an issue with grunt-usemin.
