### ISSUE TITLE
 `Cannot read property '1' of null` error

### ISSUE THREAD

**Issue by evxn** [yeoman/grunt-filerev#86]
The problem seems to be in this lines:

    var matches = convert.mapFileCommentRegex.exec(fileContents);
    var sourceMapFile = matches[1] || matches[2]; // 1st is single line, 2nd is multiline

`regex.exec` returns `null` when it didn't match anything.

**Comment by sindresorhus** [comment]
// @yoshokatana

**Comment by yoshokatana** [comment]
Hmm. Those shouldn't execute if there is no sourcemap comment. @evxn what does the source file look like?

**Comment by yoshokatana** [comment]
I added a catch around that code in #87, but I want to add a test case before that PR is merged.

**Comment by evxn** [comment]
@yoshokatana
You're right, I inspected our compiled CSS file and there is no sourceMappingURL comment in it. Looks like it was erased from there during one of the previuos build steps (thanks for pointing that out). Actually this comment is not mandatory:  X-SourceMap header can be used instead.

**Comment by yoshokatana** [comment]
Ahh, interesting. I'm not sure how we should handle X-SourceMap header. Does #87 work properly in this use case?
