### ISSUE TITLE
Always the same md5 on a single file 

### ISSUE THREAD

**Issue by be-codified** [yeoman/grunt-filerev#88]
Hi,

by using plugin I am always getting the same md5 - custom-styles.min.8a248d54.css

Am I doing something wrong?

**Comment by eddiemonge** [comment]
Have you changed the file at all?

**Comment by be-codified** [comment]
I guess this was the issue. Now the filename is custom-styles.min.b97454e0.css

Thank you for the help @eddiemonge, I will close this one down.
