### ISSUE TITLE
Bump up npm version

### ISSUE THREAD

**Issue by shaneeb** [yeoman/grunt-filerev#89]
The latest commit 787bef989d9a4ca75f23f91915fdbc14a1630b32 adds check around the regexp for matching sourceMappingUrl. With the latest version on npm, processing any file that doesn't have sourceMap comment fails with the error *Cannot read property '1' of null*. This is a minor yet important fix so should be pushed to npm asap.

**Comment by eddiemonge** [comment]
done https://github.com/yeoman/grunt-filerev/releases/tag/v2.3.1

**Comment by shaneeb** [comment]
Thanks for the quick turnaround!
