### ISSUE TITLE
CSS and child partial link replace

### ISSUE THREAD

**Issue by tangorri** [yeoman/grunt-filerev#98]
Actually everything I have deplared in my index.html (build) is well renames and reference are ok in index.html. I wonder If can I do the same for the url in css (font url for exemple)
And I wonder how I can replace src (for example) path in "child" template.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
